"""

Revision ID: 230cd09bd25b
Revises: 8f8d1407df7c
Create Date: 2024-10-08 11:25:48.000759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230cd09bd25b'
down_revision = '8f8d1407df7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcastmessage', sa.Column('user_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcastmessage', 'user_id')
    # ### end Alembic commands ###
