"""

Revision ID: 8f8d1407df7c
Revises: ce36fdad67cc
Create Date: 2024-10-08 11:15:06.772739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8d1407df7c'
down_revision = 'ce36fdad67cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminmessage',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('message_id', 'id', name=op.f('pk_adminmessage')),
    sa.UniqueConstraint('message_id', name=op.f('uq_adminmessage_message_id'))
    )
    op.create_table('broadcastmessage',
    sa.Column('broadcast_message_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['admin_message_id'], ['adminmessage.message_id'], name=op.f('fk_broadcastmessage_admin_message_id_adminmessage'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('broadcast_message_id', 'id', name=op.f('pk_broadcastmessage')),
    sa.UniqueConstraint('broadcast_message_id', name=op.f('uq_broadcastmessage_broadcast_message_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broadcastmessage')
    op.drop_table('adminmessage')
    # ### end Alembic commands ###
