"""

Revision ID: ce36fdad67cc
Revises: 0ce12bb80de3
Create Date: 2024-10-08 10:28:30.151634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce36fdad67cc'
down_revision = '0ce12bb80de3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
